### ISSUE TITLE
Why meta...

### ISSUE THREAD

**Issue by marcoscaceres** [adrianhopebailie/web-monetization#15]
Semantically, the web monetization meta information seems to form a `link` relationship. Should we use link instead?

**Comment by sublimator** [comment]
Can you expand upon this? I'm not super familiar with `link` ... uhm ... tags?

**Comment by marcoscaceres** [comment]
Sure, each tag has very specific behavior in the browser. In particular `link` is wired up to retrieve resources/links (e.g., style sheets)... so there is network machinery underlying the implementation of the link tag. Again, not to throw you in the deep end, but just scan around a little bit of Gecko's link implementation to get an idea... or just to see how crazy the backing implementation is 😂

https://github.com/mozilla/gecko-dev/blob/master/dom/html/HTMLLinkElement.cpp

**Comment by sublimator** [comment]
Lol, cheers, grabbing dinner this side of the world :) I will look later.

Keen to see how this fits in with potentially dynamic (read JS injected)
monetization tags (be it link or meta or some body level wrapper or
whatever)

When I think of “parser” I am imagining you are referring to the bytes to
DOM level stage which wouldn’t, afaik, cover the dynamic case?

**Comment by marcoscaceres** [comment]
Correct, it wouldn’t... but it could cover any preconnection to a monetization server, for instance. Dynamic includes would be covered separately.

**Comment by adrianhopebailie** [comment]
Kamino closed and cloned this issue to [interledger/webmonetization.org](https://github.com/interledger/webmonetization.org/issues/19)
