### ISSUE TITLE
Well formed and malformed meta tags

### ISSUE THREAD

**Issue by marcoscaceres** [adrianhopebailie/web-monetization#17]
Similarly, we probably need to provide a validator and respective validation algorithms (see payment request for various examples of validators... e.g., for PMIs https://www.w3.org/TR/payment-method-id/#dfn-validate-a-payment-method-identifier ).

**Comment by adrianhopebailie** [comment]
Kamino closed and cloned this issue to [interledger/webmonetization.org](https://github.com/interledger/webmonetization.org/issues/21)
