### ISSUE TITLE
Defining network behavior

### ISSUE THREAD

**Issue by marcoscaceres** [adrianhopebailie/web-monetization#19]
The spec says: 
> This header MUST always be sent on [[SPSP]] queries for Web Monetization.

The current behavior is bit under-defined... we need to hook into the appropriate network infrastructure to send things at the appropriate time.

**Comment by adrianhopebailie** [comment]
Kamino closed and cloned this issue to [interledger/webmonetization.org](https://github.com/interledger/webmonetization.org/issues/22)
