### ISSUE TITLE
Issues on Explainer

### ISSUE THREAD

**Issue by sharafian** [adrianhopebailie/web-monetization#2]
Just writing up my comments on `explainer.md`

> Web Monetization is a proposed API standard that allows websites to request a stream of very small payments from a user e.g. fractions of a cent.

Payments are coming from Coil, not the user.

> It must not be possible for the user's Web Monetization provider to get details of a user's browsing history.

I disagree with this point. Coil chooses not to have this information but I don't see why that should be restricted as a part of the standard. Although even Coil accesses the browser history and DOM events on the client side to do basic things like bandwidth adjustment or even enforcing the user's preferences to pay/not pay different pieces of content. From the standard's point of view that would mean the Web Monetization provider is getting the browsing history, even though it isn't going to any servers. Or what if I want to self-host my WM provider and it's fine with me for it to know my browsing history? 

I think it's also odd because the payment pointer itself is something that Coil _doesn't_ learn, but here it's presented as a piece of information that is acceptable to send to the WM provider. But the payment pointer is something that we want to keep private from the WM provider with the same level of privacy as the actual URLs that the browser is visiting.

> Web Monetization Provider: The entity that sends money on behalf of the user to the website. More details...

The provider is both the entity that pays the website and the code loaded into the user's browser that communicates to the entity that sends the payments. It's important to distinguish these because from a privacy perspective it matters a lot which one we're referring to.

> 2. The browser instructs the user's WM provider to start sending payments to the website, providing the website's receiving address and a random correlation id (generated for each page refresh or visit).

Right here it seems like the "WM provider" is referring to the WM provider's software component loaded into the user's browser. But earlier in the document it seems like these two things were purposely distinguished from one another.

> 7. The web page can connect to its own backend systems to verify that the payment was received (using the correlation id to correlate the incoming payment stream with the current page visit).

In practice the more likely scenario is that the user sends the correlation ID when they request content from the backend, and the backend will communicate to the WM receiver to confirm that funds were received. Theoretically this flow you described could also be used to make client-side soft paywalls a little bit harder but it's different from how we actually lock content.

> In-keeping with the trend toward streaming APIs, the API surface could be updated to implement the stream API rather than repeated events.

I'm not an expert but it seems like the Streams API is oriented specifically towards splitting up data payloads. It doesn't seem like it would be very useful as a general pattern for repeated events.

> Websites that use Web Monetization require a receiving address for their payments (which they will get from their WM receiver) and insert this into the appropriate meta tag as EITHER a URL or a Payment Pointer.

I think this use of "receiving address" is confusing because you refer to the payment pointer as a "payment initiation endpoint" earlier in the paragraph. I think using "payment initiation endpoint" would be best because an "address" implies that it's a passive payment destination whereas SPSP requires an actively running and accessible endpoint.

> Initially the browser sets document.monetization.state to pending.

This should only be set to pending if the browser is attempting to pay (i.e. the browser has a registered Web Monetization handler and the handler is willing to pay). This makes me think we might want a state where the browser supports web monetization but has no intention to pay the current page.

> The browser invokes the user's Web Monetization Provider passing it the requestId and paymentPointer.

Just the requestId and paymentPointer are insufficient for a WM provider to actually do its job. 

>  The provider MAY decide to stop/start payment at any time, e.g. if the user is idle or backgrounds the page.

what's the nature of the provider's ability to access this information?

> It should also be possible to tell the browser NOT to pay a particular website any money. (Use case: web user needs to visit a monetized web site with unpalatable viewpoints etc and doesn't want to contribute financially.)

I think it's fine to set this at the browser level, but it should also be allowed for a Web Monetization provider to make this decision. A big factor in choosing your WM provider will be picking one that pays well to good sites and doesn't pay to bad sites.

> Bruce reckons that document.monetization shouldn't be present in this case - site should not be able to guess that their site is blocked because document.monetization.state never moves from pending.

I think that document.monetization should either be in a state like 'stopped' or should not be present at all. Hanging in 'pending' just causes unnecessary lagginess in the page's logic.

> It should also be possible to tell the browser a list of sites which can optionally be paid more than usual sum. (Use case: web user visits favourite charity's website.) Note: For privacy reasons the provider does not know which site the user is visiting.

Again, I think this decision should be made in the provider, not the browser. A manually compiled list isn't going to be a practical use here. And because things like "bandwidth tiers" aren't going to translate across providers I can't really think of a useful way to represent this information.

**Comment by marcoscaceres** [comment]
> I disagree with this point. Coil chooses not to have this information but I don't see why that should be restricted as a part of the standard.

Generally, we (browsers) want to discourage any form of tracking. A browser also won't reveal any browsing history to a third-party, so no API will give up any information.   

>  Although even Coil accesses the browser history and DOM events on the client side to do basic things like bandwidth adjustment or even enforcing the user's preferences to pay/not pay different pieces of content.

I guess you mean just on a particular first-party site (and obviously not the whole browser history)... which is fine :)

 > Or what if I want to self-host my WM provider and it's fine with me for it to know my browsing history?

Again, depends on the scope of "browsing history": No web browser would ever reveal that to a third party (hence active measures around tracking protection).

**Comment by sublimator** [comment]
> No web browser would ever reveal that to a third party

Web Extensions are pretty powerful :) Ben's pointing out that the coil extension currently does a lot `client side` (not sending sensitive data to coil servers [1]) using those facilities that everyone seems quite fine with. There is a review process for extensions. 

Why can't a WM provider code get as privileged access to location data as extensions, as long as they swear to use the data client side ? 

Was giving that much access to content scripts a mistake? Are all the browser vendors moving towards Apple level strictness ?  When is that happening ?

> obviously not the whole browser history

I think he's referring to the content script facilities of wext 

[1] With the exception of so called `adapted` sites like youtube, where the extension will do an *anonymous* (no auth) lookup of a youtube video's channel owner and check if it has been `claimed` and a payment pointer has been associated.

**Comment by sublimator** [comment]
@marcoscaceres

What are your thoughts on the "automatic" payment aspect of WM ? I have used the Web Bluetooth API before and note that you can only initiate connection requests inside call stacks of a user event like onclick. 

Is that likely to be a big issue?

**Comment by marcoscaceres** [comment]
> Is that likely to be a big issue?

It really depends - but I don't think it's a big issue: it's could work like any other permission, whereby the user grants the site the ability to be paid automatically if various conditions are met... the "conditions" are where it gets tricky, but I guess that's what will be fleshed out in the spec.

**Comment by sublimator** [comment]
@marcoscaceres 

I see. Thanks.

**Comment by adrianhopebailie** [comment]
All of these issues were addressed by the latest updates.
