### ISSUE TITLE
Support for multiple concurrent providers

### ISSUE THREAD

**Issue by adrianhopebailie** [adrianhopebailie/web-monetization#8]
Per comment from @sublimator in #3 

> something implied in the images above, while not really relevant to the discussion above is use of multiple providers concurrently. Is that something that could/should be supported ?

I think that with the browser as an intermediary there is nothing preventing a user having multiple providers running concurrently.

The website is notified on incoming payments but not who they came from so it is opaque to it anyway if they come from one or more providers.

**Comment by LonMcGregor** [comment]
Multiple providers would be good - end users may not want to sign up to a 10s of different services for each website they visit. so it makes sense for websites to support as many as possible to make it easier to take part in monetisation.

**Comment by brucelawson** [comment]
"it makes sense for websites to support as many as possible" < the beauty of this becoming (we hope) an open standard is that websites don't need to do anything other than include the metatag and listen for the JS events - that supports one or one thousand payment providers.

**Comment by sublimator** [comment]
The providers would all use the same correlation id ? What issues, if any ?

**Comment by sharafian** [comment]
When we say multiple concurrent providers are we talking about being on a page and more than one provider at once is sending micropayments? That would make the events much harder to handle (both client and server-side) and would be very strange

I think it might make sense to have different WM providers installed though, with one being the default, and then you could change the WM provider you're using for certain sites

**Comment by sublimator** [comment]
Yes, experience trumps theory

**Comment by sublimator** [comment]
> more than one provider at once is sending micropayments? 

Yes, that's what I was wondering about.

> Yes, experience trumps theory

That's a bit cryptic I guess :) 

It means I would believe you when you say "make the events much harder to handle" as you've had the experience of full e2e WM development. 

If it would make the most common case of a single provider paying out that much more complicated then it's probably not a good idea?

**Comment by sharafian** [comment]
Yeah I just can't imagine any benefit to multiple providers paying at once, but I can see many potential downsides

**Comment by adrianhopebailie** [comment]
Based on the Agent/Sender model we've adopted I'd say it's unlikely the user will have multiple agents (deciding how much to pay) but it they could have multiple senders.

I think we can leave it open to browsers to decide how the allow users to decide which sender is used at any time.
